version: "3"

services:
  backend:
    build:
      context: ./icin_backend
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./icin_frontend
    ports:
      - 80:80
    links:
      - backend
    depends_on:
      - backend
