version: "3"

services:
  backend:
    image: x4teen/icin_backend
    build:
      context: ./icin_backend
    ports:
      - 8080:8080

  frontend:
    image: x4teen/icin_frontend
    build:
      context: ./icin_frontend
    ports:
      - 80:80
    links:
      - "backend: icin_backend"
    depends_on:
      - backend
